# Generated by Django 5.0.2 on 2024-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
