# Generated by Django 5.0.2 on 2024-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_bookmark_is_bookmarked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('blog',)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('blog',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogs/blog_images'),
        ),
    ]
